/*
 * Button Debounce Simulation
 *
 * MODELS:    A noisy tactile button on a microcontroller GPIO pin.
 *            The debounce algorithm is real (identical to production embedded code).
 * SIMULATED: The "noisy input" is generated by a pseudo-random sequence.
 * REAL HW:   Feed gpio_read() from a real MCU pin; keep debounce logic unchanged.
 *
 * Compile: gcc button_debounce_sim.c -o button_debounce_sim.exe
 */
#include <stdio.h>
#include "gpio_simulated.h"

#define BUTTON_PIN    2
#define DEBOUNCE_MS  50    /* debounce window */
#define SIM_STEPS   200    /* simulated tick steps of 10 ms each */
#define TICK_MS      10

/* Generate a realistic noisy button press pattern */
static int noisy_button_sequence[SIM_STEPS];

static void generate_noisy_press(int *seq, int steps) {
    unsigned int rng = 0xDEADBEEF;
    int pressed = 0;
    for (int i = 0; i < steps; i++) {
        rng = rng * 1664525u + 1013904223u;
        /* Press events at t=30 and t=120 */
        if (i == 30 || i == 120) pressed = !pressed;
        /* Add noise: random glitches */
        int noise = ((rng >> 16) & 0xF) < 2;   /* ~12% chance of glitch */
        seq[i] = pressed ^ noise;
    }
}

int main(void) {
    printf("=== Button Debounce Simulation ===\n");
    printf("Debounce window: %d ms\n\n", DEBOUNCE_MS);

    generate_noisy_press(noisy_button_sequence, SIM_STEPS);
    gpio_init();
    gpio_set_mode(BUTTON_PIN, GPIO_INPUT);

    int  debounced     = 0;
    int  last_raw      = 0;
    long stable_since  = 0;
    int  changes       = 0;
    int  raw_changes   = 0;

    printf("%-6s %-5s %-10s  %s\n", "t(ms)", "Raw", "Debounced", "Event");
    printf("%-6s %-5s %-10s  %s\n", "------", "-----", "----------", "-----");

    for (int i = 0; i < SIM_STEPS; i++) {
        long t = i * TICK_MS;
        int raw = noisy_button_sequence[i];
        _sim_pins[BUTTON_PIN].value = raw;

        if (raw != last_raw) { raw_changes++; last_raw = raw; stable_since = t; }

        if (t - stable_since >= DEBOUNCE_MS && raw != debounced) {
            debounced = raw;
            changes++;
            printf("%-6ld %-5d %-10d  *** %s ***\n",
                   t, raw, debounced, debounced ? "PRESSED" : "RELEASED");
        } else if (i % 10 == 0) {
            printf("%-6ld %-5d %-10d\n", t, raw, debounced);
        }
    }

    printf("\nRaw signal changes : %d\n", raw_changes);
    printf("Debounced events   : %d  (noise eliminated)\n", changes);
    return 0;
}
